### PR TITLE
Adding example-bot an betting-bot to stack

### PR DESCRIPTION
**Pull request by kevkevinpal**
adding the example bot and betting bot to the stack

changed the bots doc will probably try and create a doc in the future to help make the deployment to a persons actual node easier.

Added some changes to generate tokens for the bots in `/relay/botConfig.json`

As of now there is not an easy way to import a bot you made or make a new bot, will need to make a script to import or generate new bot to develop on

One of the first few PR's to making an amazing dev environment for bot creators

### CODE REVIEW

**Comment by Evanfeenstra** [comment]
Very cool @kevkevinpal! Thinking about it, I think maybe the bots should live in a different docker-compose file, as they are not necessarily core pieces of the infra. And beginners can get started right away without worrying about submodules (or waiting for npm install in the bot libs)

I just learned you can run different docker-compose files together like `docker-compose -f docker-compose.yml -f alts/bots.yml`. Can you set it up like that?

**Comment by kevkevinpal** [comment]
> Very cool @kevkevinpal! Thinking about it, I think maybe the bots should live in a different docker-compose file, as they are not necessarily core pieces of the infra. And beginners can get started right away without worrying about submodules (or waiting for npm install in the bot libs)
> 
> I just learned you can run different docker-compose files together like `docker-compose -f docker-compose.yml -f alts/bots.yml`. Can you set it up like that?

Yea that makes sense I can try setting it up like that

**Comment by kevkevinpal** [comment]
> Very cool @kevkevinpal! Thinking about it, I think maybe the bots should live in a different docker-compose file, as they are not necessarily core pieces of the infra. And beginners can get started right away without worrying about submodules (or waiting for npm install in the bot libs)
> 
> I just learned you can run different docker-compose files together like `docker-compose -f docker-compose.yml -f alts/bots.yml`. Can you set it up like that?

Updated in c5da8ae

**Comment by kevkevinpal** [comment]
Need to push another change for some reason the env vars are not showing up in the bots when we do it this way

**Comment by Evanfeenstra** [comment]
beautiful

**Pull request merged**
