### PR TITLE
Adding proxy to stack

### PR DESCRIPTION
**Pull request by kevkevinpal**
This diff is a bit messy right now but it is working if you have access to the proxy repo

running `docker-compose up -d` should get this up and running the other yml files I'm not using right now and need to update

this should create two lite nodes in the NODES.json file that we can then use for testing

still some work to do like decoupling the proxy part from everything else but the base is here

I've been testing with this test on relay
`npx ava src/tests/controllers/chatPayment.test.ts --verbose --serial --timeout=2m`

### CODE REVIEW

**Comment by kevkevinpal** [comment]
ok updated the `alts/proxy.yml` file so now running

`docker-compose -f alts/proxy.yml --project-directory . up -d`

will get it up and running

**Comment by Evanfeenstra** [comment]
wooooottt!!! any blockers or things that aren't working currently?

**Comment by kevkevinpal** [comment]
> wooooottt!!! any blockers or things that aren't working currently?

The only issues I can see coming up is when trying to build proxy as it is a private repo and also some of the tests will fail since lite users can't make tribes and ect.

So there might be some custom logic need when we run tests with lite users

**Comment by Evanfeenstra** [comment]
proxy users should be able to make tribes, its just blocked in the app. its a scaling issue, not a fundamental issue for proxy. 

How about proxy->proxy messages, is that working now?

**Comment by kevkevinpal** [comment]
> 

let me try more tests didn't realize that it was just restricted in the app

**Comment by kevkevinpal** [comment]
just tried this test @Evanfeenstra and it worked!
`npx ava src/tests/controllers/tribe.test.ts --verbose --serial --timeout=2m`

**Comment by kevkevinpal** [comment]
I think this is good now, I'ma merge it

**Pull request merged**
