### PR TITLE
Create clightning docker compose

### PR DESCRIPTION
**Pull request by omoniyi24**
I made a solution to issue #42

### CODE REVIEW

**Comment by kevkevinpal** [comment]
Looks like cln is waiting on the 'inital block download' is that where it is for you @omoniyi24

**Comment by omoniyi24** [comment]
> Looks like cln is waiting on the 'inital block download' is that where it is for you @omoniyi24

Yeah, I noticed the same behavior after the feerate estimate.

**Comment by kevkevinpal** [comment]
> 

I'm pretty sure that should be fine though just need to write a script to do the ibd since it might not be automatic, Important part is that cln is connected to bitcoind

**Comment by kevkevinpal** [comment]
PR is looking good sent over 250k sats just will wait for Evan to give a look and merge it 🚀

**Comment by Evanfeenstra** [comment]
Sweet!

**Pull request merged**
