### PR TITLE
Aperture support to sphinx stack

### PR DESCRIPTION
**Pull request by bucko13**
Adds alt docker compose configs for hooking up an lsat based paywall using aperture hooked up to alice's node. 

Still want to fine tune some of the configs so that all the proxying works properly but these configs work as is such that protected routes require an LSAT to be paid.

### CODE REVIEW

**Comment by kevkevinpal** [comment]
Hey @bucko13 I'd be interested in testing this out but I'm not too familiar with LSATS and aperture, what should I do to try it out

also if you don't think its just ready yet I can wait too :)

**Comment by bucko13** [comment]
@kevkevinpal definitely not quite ready although it is in a state where it can be played with a little bit but the config is just protecting an arbitrary route for now. I put it up as a draft in case there were any comments about how the configs themselves are setup. I could probably put it such that every route is whitelisted and so nothing protected by a 402 and then do a separate PR when the endpoints on meme server are ready. 

Basically how this is supposed to work is that aperture is a proxy in front of meme and then any requests that are configured to be protected will return a 402 endpoint requiring payment before granting access. I’ve put it as a separate “alt” docker compose so that the default configuration doesn’t change as per @Evanfeenstra’s suggestion which included a couple other small tweaks to make meme also configurable to be behind the proxy and only accessible via aperture.

**Comment by Evanfeenstra** [comment]
Very cool! Config setup looks great to me

**Comment by bucko13** [comment]
Alright, I think this is good for now. It will "protect" an API route that we probably don't want to protect just yet, but you have to want to deliberately set it up that way with the separate configs so it should be safe in any case. The routes might change as the meme work kicks off anyway.

**Comment by Evanfeenstra** [comment]
sweeeeeeeet

**Pull request merged**
